[package]
name = "problem_4"
version = "0.1.0"
authors = ["RÃ©mi Granotier <remigranotier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]